dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: field-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: rest-access-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
